services:
  emqx:
    image: emqx:latest
    container_name: emqx
    ports:
      - "18083:18083"
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"

  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    ports:
      - "2020:1880"
    volumes:
      - nodered_data:/data

volumes:
  nodered_data:
